os: linux
dist: focal
language: python

python:
  - "3.8.5"

install:
  - sudo apt-get install build-essential wget git desktop-file-utils -y

before_script:
  - git clone https://github.com/Avlye/PacketTracer-AppImage
  - cd PacketTracer-AppImage/
  - wget --quiet -c https://archive.org/download/packettracer730mac_202002/PacketTracer_730_amd64.deb
  - wget --quiet https://github.com/AppImage/pkg2appimage/raw/master/pkg2appimage
  - chmod +x pkg2appimage

script:  
  - ./pkg2appimage PacketTracer.yml
  - ls -asl && find out
  

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Gabriel Almir"
  - git config --local user.email "avlye@outlook.com"
  - export TRAVIS_TAG=${Packet Tracer - App Image:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  token: $GITHUB_TOKEN
  file: "../out/Packet_Tracer_7.3.0-.glibc2.27-x86_64.AppImage"

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
