os: linux
dist: focal
language: python

python:
  - "3.8.5"

install:
  - sudo apt-get install build-essential wget git desktop-file-utils -y

before_script:
  - git clone https://github.com/Avlye/PacketTracer-AppImage
  - cd PacketTracer-AppImage/
  - wget https://github.com/AppImage/pkg2appimage/raw/master/pkg2appimage
  - chmod +x pkg2appimage

script:
  - ./pkg2appimage PacketTracer.yml
  - ls -asl && find out

deploy:
  provider: releases
  token: $GITHUB_TOKEN
  file_glob: true
  file: "out/*"
  overwrite: true
  cleanup: false

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
