os: linux
dist: bionic
language: python

script:
  - git clone https://github.com/Avlye/PacketTracer-AppImage
  - cd PacketTracer-AppImage/
  - wget https://github.com/AppImage/pkg2appimage/raw/master/pkg2appimage
  - chmod +x pkg2appimage
  - ./pkg2appimage PacketTracer.yml
  - ls -lh out/*
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh out/*

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
