name: Build AppImage

# Controls when the action will run.
# Workflow runs when manually triggered using the UI or API.
# [push] means the workflow is triggered on pushes to the repository.
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Build AppImage
        uses: AppImageCrafters/build-appimage-action@master
        env:
          UPDATE_INFO: gh-releases-zsync|Avlye|PacketTracer-AppImage|latest|*x86_64.AppImage.zsync
        with:
          # appimage-builder recipe file
          recipe: PacketTracer.yml
      - uses: actions/upload-artifact@v2
        with:
          name: AppImage
